/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctk.vo;

import java.io.*;

/**
 * DepartmentsKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/18/2016.
 */
public class DepartmentsKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for deptNo. */
    private String deptNo;

    /**
     * Empty constructor.
     */
    public DepartmentsKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public DepartmentsKey(
        String deptNo
    ) {
        this.deptNo = deptNo;
    }

    /**
     * Gets deptNo.
     *
     * @return Value for deptNo.
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * Sets deptNo.
     *
     * @param deptNo New value for deptNo.
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof DepartmentsKey))
            return false;

        DepartmentsKey that = (DepartmentsKey)o;

        if (deptNo != null ? !deptNo.equals(that.deptNo) : that.deptNo != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = deptNo != null ? deptNo.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "DepartmentsKey [deptNo=" + deptNo +
            "]";
    }
}

