/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctk.vo;

import java.io.*;

/**
 * Departments definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/18/2016.
 */
public class Departments implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for deptName. */
    private String deptName;

    /**
     * Empty constructor.
     */
    public Departments() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public Departments(
        String deptName
    ) {
        this.deptName = deptName;
    }

    /**
     * Gets deptName.
     *
     * @return Value for deptName.
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * Sets deptName.
     *
     * @param deptName New value for deptName.
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Departments))
            return false;

        Departments that = (Departments)o;

        if (deptName != null ? !deptName.equals(that.deptName) : that.deptName != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = deptName != null ? deptName.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Departments [deptName=" + deptName +
            "]";
    }
}

