/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctk.vo;

import java.io.*;

/**
 * EmployeesKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/18/2016.
 */
public class EmployeesKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for empNo. */
    private int empNo;

    /**
     * Empty constructor.
     */
    public EmployeesKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public EmployeesKey(
        int empNo
    ) {
        this.empNo = empNo;
    }

    /**
     * Gets empNo.
     *
     * @return Value for empNo.
     */
    public int getEmpNo() {
        return empNo;
    }

    /**
     * Sets empNo.
     *
     * @param empNo New value for empNo.
     */
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof EmployeesKey))
            return false;

        EmployeesKey that = (EmployeesKey)o;

        if (empNo != that.empNo)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = empNo;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "EmployeesKey [empNo=" + empNo +
            "]";
    }
}

