/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctk.ignite.vo;

import java.io.*;

/**
 * SalariesKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/17/2016.
 */
public class SalariesKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for empNo. */
    private int empNo;

    /** Value for fromDate. */
    private java.sql.Date fromDate;

    /**
     * Empty constructor.
     */
    public SalariesKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public SalariesKey(
        int empNo,
        java.sql.Date fromDate
    ) {
        this.empNo = empNo;
        this.fromDate = fromDate;
    }

    /**
     * Gets empNo.
     *
     * @return Value for empNo.
     */
    public int getEmpNo() {
        return empNo;
    }

    /**
     * Sets empNo.
     *
     * @param empNo New value for empNo.
     */
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }

    /**
     * Gets fromDate.
     *
     * @return Value for fromDate.
     */
    public java.sql.Date getFromDate() {
        return fromDate;
    }

    /**
     * Sets fromDate.
     *
     * @param fromDate New value for fromDate.
     */
    public void setFromDate(java.sql.Date fromDate) {
        this.fromDate = fromDate;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof SalariesKey))
            return false;

        SalariesKey that = (SalariesKey)o;

        if (empNo != that.empNo)
            return false;

        if (fromDate != null ? !fromDate.equals(that.fromDate) : that.fromDate != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = empNo;

        res = 31 * res + (fromDate != null ? fromDate.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "SalariesKey [empNo=" + empNo +
            ", fromDate=" + fromDate +
            "]";
    }
}

