/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctk.ignite.vo;

import java.io.*;

/**
 * Salaries definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/17/2016.
 */
public class Salaries implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for salary. */
    private int salary;

    /** Value for toDate. */
    private java.sql.Date toDate;

    /**
     * Empty constructor.
     */
    public Salaries() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public Salaries(
        int salary,
        java.sql.Date toDate
    ) {
        this.salary = salary;
        this.toDate = toDate;
    }

    /**
     * Gets salary.
     *
     * @return Value for salary.
     */
    public int getSalary() {
        return salary;
    }

    /**
     * Sets salary.
     *
     * @param salary New value for salary.
     */
    public void setSalary(int salary) {
        this.salary = salary;
    }

    /**
     * Gets toDate.
     *
     * @return Value for toDate.
     */
    public java.sql.Date getToDate() {
        return toDate;
    }

    /**
     * Sets toDate.
     *
     * @param toDate New value for toDate.
     */
    public void setToDate(java.sql.Date toDate) {
        this.toDate = toDate;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Salaries))
            return false;

        Salaries that = (Salaries)o;

        if (salary != that.salary)
            return false;

        if (toDate != null ? !toDate.equals(that.toDate) : that.toDate != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = salary;

        res = 31 * res + (toDate != null ? toDate.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Salaries [salary=" + salary +
            ", toDate=" + toDate +
            "]";
    }
}

